// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNKtoSOjKzAf1hS72VLM_flLcPt8PNof8',
    appId: '1:254886564090:web:e4214f7d6ba7a1a0baf943',
    messagingSenderId: '254886564090',
    projectId: 'mega-inscriber-xcbh2',
    authDomain: 'mega-inscriber-xcbh2.firebaseapp.com',
    storageBucket: 'mega-inscriber-xcbh2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNKtoSOjKzAf1hS72VLM_flLcPt8PNof8',
    appId: '1:254886564090:android:3b29c9fe8713aa67',
    messagingSenderId: '254886564090',
    projectId: 'mega-inscriber-xcbh2',
    storageBucket: 'mega-inscriber-xcbh2.firebasestorage.app',
  );
}
